[project]
name = "MusicTerm"
version = "0.0.5"
authors = [{ name = "ZachVFX", email = "zachallrd@gmail.com" }]
description = "play music from your termninal."
readme = "README.md"
requires-python = "~=3.12"
dependencies = [
    "just-playback>=0.1.8",
    "msgspec>=0.19.0",
    "pydub>=0.25.1",
    "pytubefix>=8.12.1",
    "textual>=1.0.0",
    "tomli-w>=1.2.0",
    "ytmusicapi>=1.10.1",
    "loguru>=0.7.3",
    "ffmpeg>=1.4",
    "humanize>=4.12.1",
    "mpris-server>=0.9.0; sys_platform != 'win32'",
    "win11toast>=0.35; sys_platform == 'win32'",
]

[project.urls]
Homepage = "https://github.com/ZachVFXX/PyMusicTerm"
Issues = "https://github.com/ZachVFXX/PyMusicTerm/issues"
